version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build: .
    image: ingester:0.1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 80M
      restart_policy:
        condition: on-failure
    ports:
    - "4000:8083"
    networks:
    - webnet
networks:
  webnet:
